### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by elbogi** [maddox/magic-cards#16]
Magic Card installed as per instructed with docker-compose provided from project. I have however removed the Sonos part since I am not using Sonos at the moment. Everything works fine, I get Spotify to play through automation in Home-Assistant. But after some hours (uncertain how long) something happens and when trying to read a card nothing happens and I get the following error:

```
[1] events.js:165
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: ENODEV: no such device, read
[1] Emitted 'error' event at:
[1]     at ReadStream.<anonymous> (/usr/src/app/scanner/node_modules/input-event/lib/index.js:45:10)
[1]     at ReadStream.emit (events.js:180:13)
[1]     at fs.read (fs.js:2116:12)
     at FSReqWrap.wrapper [as oncomplete] (fs.js:673:17)
[1] error Command failed with exit code 1.
[1] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] error Command failed with exit code 1.
[1] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn scanner exited with code 1
```
Only solution so far has been to restart docker. 

**docker-compose.yaml** file:
```
version: "3"

services:
  magic-cards:
    image: jonmaddox/magic-cards:latest
    container_name: magic-cards
    network_mode: host
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - $PWD/magic-cards/config:/usr/src/app/config
    devices:
      - "/dev/input/event0:/dev/input/event0"
```

**config.json**:
```
{
  "input_device": "event0",
  "spotify": {
    "clientID": "0000000000000000000",
    "clientSecret": "000000000000000000000"
  }
}
```

**actions.json**:
```
{
  "Home Assistant": {
    "type": "home_assistant",
    "host": "x.x.x.x",
    "port": "xxx",
    "ssl": false,
    "password": "MyPassword"
  }
}
```
